module.exports = {
  rules: {
    "@typescript-eslint/no-unused-vars": [
      "error",
      { argsIgnorePattern: "^ignored", ignoreRestSiblings: true },
    ],
    "@typescript-eslint/no-var-requires": "off",
    "react/button-has-type": "error",
    "react/boolean-prop-naming": [
      "error",
      { rule: "^(is|has)[A-Z]([A-Za-z0-9]?)+" },
    ],
    "react/destructuring-assignment": ["warn", "always"],
    "react/display-name": "off",
    "react/function-component-definition": [
      "error",
      {
        namedComponents: "arrow-function",
        unnamedComponents: "arrow-function",
      },
    ],
    "react/jsx-closing-tag-location": "error",
    "react/jsx-handler-names": "error",
    "react/jsx-key": "error",
    "react/jsx-newline": ["warn", { prevent: true }],
    "react/jsx-no-useless-fragment": "error",
    "react/jsx-no-target-blank": "error",
    "react/jsx-sort-props": [
      "error",
      {
        callbacksLast: true,
        ignoreCase: false,
        noSortAlphabetically: false,
        reservedFirst: true,
        shorthandFirst: true,
      },
    ],
    "react/no-access-state-in-setstate": "error",
    "react/no-array-index-key": "error",
    "react/no-children-prop": "error",
    "react/no-danger-with-children": "error",
    "react/no-danger": "error",
    "react/no-deprecated": "error",
    "react/no-direct-mutation-state": "error",
    "react/no-find-dom-node": "error",
    "react/no-this-in-sfc": "error",
    "react/no-typos": "error",
    "react/no-unescaped-entities": "error",
    "react/no-unknown-property": "error",
    "react/no-unsafe": "error",
    "react/no-unstable-nested-components": "error",
    "react/no-unused-state": "error",
    "react/prefer-es6-class": "error",
    "react/prop-types": "off",
    "react/react-in-jsx-scope": "off",
    "react/self-closing-comp": "error",
    "react/sort-comp": "error",
    "react/style-prop-object": "error",
    "react/void-dom-elements-no-children": "error",
  },
};
